# Configuration for Read the Docs
# https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Search engine
search:
  ignore: [search]
